# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Yoursun.me
title: Trainto.log()
email: trainto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer who lives in Seoul, Korea. Husband of my wife. Like programming,
  playing piano, driving my car and love 'Yousun'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hisblog.yoursun.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

gems: ['jekyll-paginate']
paginate: 3

disqus: 'yoursunme'
comments: true

gaaccount: UA-73310674-3
